name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      run: |
        az acr login --name ${{ secrets.REGISTRY_LOGIN_SERVER }}
    
    - name: Create Azure container environment
      run: az containerapp env create -n group-3-container-env -g  ${{ secrets.RESOURCE_GROUP }} --location francecentral
    
    - name: Deploy to Azure Container
      run: az containerapp create --resource-group ${{ secrets.RESOURCE_GROUP }} --name group-3-container --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/model_groupe3:v1 --cpu 1 --memory 2 --registry-server ${{ secrets.REGISTRY_LOGIN_SERVER }} --registry-username ${{ secrets.REGISTRY_USERNAME }} --registry-password ${{ secrets.REGISTRY_PASSWORD }} --ingress external --target-port 80 --environment group-3-container-env
    - name: Build and push image
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - run: |
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/model_groupe3:v1
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/model_groupe3:v1

    - name: Build and deploy Container App
      uses: azure/container-apps-deploy-action@v2
      with:
        appSourcePath: ${{ github.workspace }}
        acrName: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        containerAppName: group-3-container
        resourceGroup: ${{ secrets.RESOURCE_GROUP }}
        imageToDeploy: ${{ secrets.REGISTRY_LOGIN_SERVER }}/projectgroupe3:v1
        location: 'france central'
        ports: 80
        dns-name-label: projectgroupe3